version: "3"

services:
  boardgame-app:
    image: boardgame-app
    container_name: boardgame-app-container
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - PORT=9000
    restart: unless-stopped
